app:
    output_dir: './output/'    
processors:
    path: './processors/'
    queue:
        - "ChallengeOne"
        - "ChallengeTwo"
database:
    host: localhost
    database: stone_challenge
    user: postgres
    password: masterkey